### ISSUE TITLE
what is the status of this project?

### ISSUE THREAD

**Issue by hoebat** [clojure-android/lein-droid#167]
I'm wondering how this project is going, if there are any plans for improvements and if not, what are the alternatives to running clojure on android.

**Comment by ampersanda** [comment]
I don't think this project is going and I think you should look at re-natal using Clojurescript https://github.com/drapanjanas/re-natal

**Comment by alexander-yakushev** [comment]
Yeah, sorry about not answering. I don't work on this project anymore. I should put a note about that, but the guilt stops me every time :(.

**Comment by hoebat** [comment]
@alexander-yakushev: apart from the fact that you're not working on this anymore is there a reason why the project can't continue? ie. new android versions, better technologies etc.

I don't know much about android and the build process but am thinking of using this project or robovm as a way to run clojure on android. I'm not that keen on the react native route.

**Comment by alexander-yakushev** [comment]
There are a few problems that Clojure has when targeting Android: relatively big startup time, higher memory consumption, non-existent community. I never got enough people using this and working on this.  Also, the Android tooling and the ecosystem is quite volatile, so extra effort is required to keep up with it.

But the main reason why this never took off is probably because it's single-platform. When someone is keen on going an exotic route, then it makes more sense for them to take RN/other cross-platform solution than locking themselves to Android-only app.

**Comment by hoebat** [comment]
Thanks for the info. Yeah that makes sense.
