### ISSUE TITLE
:aot :all-with-unused required?  Or recommended?

### ISSUE THREAD

**Issue by wiseman** [clojure-android/lein-droid#76]
Some libraries will build with `:aot :all` but not with `:aot :all-with-unused` (e.g. see https://github.com/ptaoussanis/timbre/issues/35).  Is `:all-with-unused` required, or a good idea?  If not, should it be changed in the template to `:aot :all`?

**Comment by alexander-yakushev** [comment]
OK, this is really embarrassing that I answer this question only now. I suppose the problem is solved long ago, but still.

`:all-with-unused` is not required, although it is convenient in Android case because it ensures all namespaces to be present on the device during development. Otherwise you will have to manually load namespaces that you suddenly want to start using, which takes solid seconds and is quite annoying.

If some libraries don't work well with `:all-with-unused` you can always add the conflicting namespaces to `:aot-exclude-ns` map.

**Comment by wiseman** [comment]
OK, thanks for the answer!
